name: dendrites
description: Scala library for Reactive streaming Microservices, CQRS, Event Sourcing, & Event Logging 
author: Gary Struthers
author_email: garystruthers@earthlink.net
baseurl: /dendrites
url: http://garyaiki.github.io/dendrites/
theme: jekyll-theme-cayman